default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [admin.css, print: { media: print }, bootstrap.css, bootstrap-responsive.css]

  javascripts:    [prototype.js, jquery.js, jquery-1.6.1.min.js, symfony-toggle.js, vlir-toggle.js, bootstrap-alerts.js, page-no.js ]


  has_layout:     true
  layout:         layout
