default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, bootstrap.css, bootstrap-responsive.css, docs.css, login.css, list.css]

  javascripts:    [prototype.js, bootstrap.js, bootstrap.min.js, jquery.js, jquery-1.6.1.min.js, jquery.google_menu.js, toggleSpan.js]


  has_layout:     true
  layout:         layout
