generator:
  class: sfPropelGenerator
  param:
    model_class:           EmailAlias
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          email_alias
    with_propel_route:     1

    config:
      actions: ~
      fields:
        domainname_id: 
                label: Domain
      list:    
        title: Email aliases
        layout: stacked
        display: [local_part, destination]
        params: %%email_alias%% &rarr; %%destination%%
      filter:  
        display: [local_part, domainname_id, destination]
      form:    ~
      edit:
        display: [local_part, domainname_id, destination]    
        title: Edit Email Aliases
        fields:
           local_part:
                help: Provide the new alias name which is found before the @ sign
           destination:
                help: Provide a valid email address where the mail should be sent to
      new:
        display: [local_part, domainname_id, destination]     
        title: Add new Email Alias
        fields:
           local_part:
                help: Provide the new alias name which is found before the @ sign
           destination:
                help: Provide a valid email address where the mail should be sent to

