generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Comment
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          comment
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:
         title: Manage comment
         display: [=subject, user_id, created_at]
         layout: stacked
         params: %%subject%% - (<small>%%user%%</small> - <em>%%created_at%%</em>)
         sort: [created_at, desc]
         max_per_page: 10
         object_actions: 
                    _delete: ~
                    show: ~
                             
      filter:
         display: [ user_id, subject, message]
      form:    ~
      edit:    ~
      new:     ~
