generator:
  class: sfPropelGenerator
  param:
    model_class:           User
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user
    with_propel_route:     1

    config:
      actions: ~
      fields:  
        domainname_id:
          label: Domain Name
        fathers_name:
          label: Fathers Name
        grand_fathers_name:
          label: Grand Fathers Name
        login:
          label: Login Name
      list:
        max_per_page: 5
        object_actions:
            show : ~
            toggle_status : ~
        batch_actions:
             _delete: ~
             toggle_status : ~
             
        display: [login, full_name, status, expires_at]
      filter:  
         display: [domainname_id, name, fathers_name, grand_fathers_name, login, status, email_local_part]
      form:
         class: BackendUserForm
      edit:    
        title: Editing user "%%name%% %%fathers_name%% %%grand_fathers_name%%"
        fields:
          email_quota:
               help: Provide the quota in bytes and put S at the end of the numbers like, 500000S
      new:     
        title: Add mail user
        display: [domainname_id, name, fathers_name, grand_fathers_name, login, phone, gid, uid, status, alternate_email, email_local_part, email_quota, expires_at]
        fields:
          email_quota:
               help: Provide the quota in bytes and put S at the end of the numbers like, 500000S

